baseURL = "/"
title = "Methnula's Blog"
theme = "terminal"

[params]
  contentTypeName = "posts"
  showMenuItems = 2
  fullWidthTheme = false
  centerTheme = false

[languages]
  [languages.en]
    languageName = "English"
    title = "Methnula's Blog"

    [languages.en.params]
      subtitle = "Notes and ideas"

      [languages.en.params.logo]
        logoText = "Methnula's Blog"
        logoHomeLink = "/"
